Зубов Павел Б05-125, 2 контест, задача H
pavelleckaya/algoritmi2021-2022 pull request #6
Opened 2021-11-15 10:18 UTC by pavelleckaya

Задача на LSD, ссылка: ...

2021-11-17 20:17 UTC, ylyubimov requested changes
Давай вынесем из main'a и будем получать массив чисел на вход.
И постараемся массив чисел не превращать в массив массивов
Ну и нет ссылки

2021-11-17 20:17 UTC, ylyubimov commented on 2H.cpp
> +        for(int i = 1; i < 256; ++i){
константа 256 встречается 4ре раза!

2021-12-19 08:38 UTC, ylyubimov requested changes
выровняй табуляции(

2021-12-19 08:38 UTC, ylyubimov commented on 2H.cpp
> +	int def = 256;
во-первых, константа, а во-вторых, внутри функции element_LSD тоже она же(

2021-12-19 10:09 UTC, pavelleckaya commented on 2H.cpp
> +	int def = 256;
я занес в def константу потому что вы сказали что 4 раза используется константа и это плохо, может я просто чтото не так понял, поетому простите и не бейте если что)

2022-05-23 07:21 UTC, closed without merging